# -*- coding: utf-8 -*-
"""Crop Disease Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lw-TvQh8f1B5vy221gXmssPx5ZrglQ8
"""

# Install Kaggle
!pip install -q kaggle

from google.colab import files
files.upload()  # upload kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d emmarex/plantdisease
!unzip plantdisease.zip -d data

import tensorflow as tf

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# Correcting the path and using validation_split to create train and validation sets
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/plantvillage/PlantVillage", # Corrected root directory
    validation_split=0.2, # Use 20% of data for validation
    subset="training",
    seed=123, # Seed for reproducible split
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "data/plantvillage/PlantVillage", # Corrected root directory
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
num_classes = len(class_names)

print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)

from tensorflow.keras import layers

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.2),
])

base_model = tf.keras.applications.EfficientNetB0(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

model = tf.keras.Sequential([
    data_augmentation,
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.BatchNormalization(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

import matplotlib.pyplot as plt

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(len(acc))

plt.figure()
plt.plot(epochs_range, acc, label='Train Accuracy')
plt.plot(epochs_range, val_acc, label='Val Accuracy')
plt.legend()
plt.title("Accuracy Graph")
plt.show()

plt.figure()
plt.plot(epochs_range, loss, label='Train Loss')
plt.plot(epochs_range, val_loss, label='Val Loss')
plt.legend()
plt.title("Loss Graph")
plt.show()

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

y_true = []
y_pred = []

for images, labels in val_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

cm = confusion_matrix(y_true, y_pred)

plt.figure()
sns.heatmap(cm, annot=False)
plt.title("Confusion Matrix")
plt.show()

print(classification_report(y_true, y_pred, target_names=class_names))

base_model.trainable = True

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5
)

acc = history.history['accuracy'] + history_fine.history['accuracy']
val_acc = history.history['val_accuracy'] + history_fine.history['val_accuracy']

loss = history.history['loss'] + history_fine.history['loss']
val_loss = history.history['val_loss'] + history_fine.history['val_loss']

import matplotlib.pyplot as plt

epochs_range = range(len(acc))

plt.figure()
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.axvline(x=len(history.history['accuracy'])-1, linestyle='--')  # shows where fine-tuning starts
plt.legend()
plt.title('Training + Fine-Tuning Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.show()

plt.figure()
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.axvline(x=len(history.history['loss'])-1, linestyle='--')
plt.legend()
plt.title('Training + Fine-Tuning Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.show()

from google.colab import drive
drive.mount('/content/drive')

import os

SAVE_PATH = '/content/drive/MyDrive/crop_disease_project/'

os.makedirs(SAVE_PATH, exist_ok=True)

print("Folder created at:", SAVE_PATH)

model.save(SAVE_PATH + 'model.keras')

import json

with open(SAVE_PATH + 'class_names.json', 'w') as f:
    json.dump(class_names, f)

history_data = {
    'accuracy': acc,
    'val_accuracy': val_acc,
    'loss': loss,
    'val_loss': val_loss
}

with open(SAVE_PATH + 'history.json', 'w') as f:
    json.dump(history_data, f)

import matplotlib.pyplot as plt

epochs_range = range(len(acc))

# Accuracy Graph
plt.figure()
plt.plot(epochs_range, acc, label='Train Accuracy')
plt.plot(epochs_range, val_acc, label='Val Accuracy')
plt.legend()
plt.title('Accuracy')
plt.savefig(SAVE_PATH + 'accuracy_plot.png')
plt.close()

# Loss Graph
plt.figure()
plt.plot(epochs_range, loss, label='Train Loss')
plt.plot(epochs_range, val_loss, label='Val Loss')
plt.legend()
plt.title('Loss')
plt.savefig(SAVE_PATH + 'loss_plot.png')
plt.close()

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_true = []
y_pred = []

for images, labels in val_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

# Save classification report
report = classification_report(y_true, y_pred)

with open(SAVE_PATH + 'classification_report.txt', 'w') as f:
    f.write(report)

# Save confusion matrix
cm = confusion_matrix(y_true, y_pred)
np.save(SAVE_PATH + 'confusion_matrix.npy', cm)

!ls /content/drive/MyDrive/crop_disease_project/

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import json

SAVE_PATH = '/content/drive/MyDrive/crop_disease_project/'

# Load model
model = tf.keras.models.load_model(SAVE_PATH + 'model.keras')

# Load class names
with open(SAVE_PATH + 'class_names.json', 'r') as f:
    class_names = json.load(f)

from google.colab import files
uploaded = files.upload()

img_path = list(uploaded.keys())[0]
print("Using image:", img_path)

from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input
import numpy as np

IMG_SIZE = (224, 224)

img = image.load_img(img_path, target_size=IMG_SIZE)
img_array = image.img_to_array(img)

# Correct preprocessing
img_array = preprocess_input(img_array)

img_array = np.expand_dims(img_array, axis=0)

predictions = model.predict(img_array)

predicted_class = class_names[np.argmax(predictions)]
confidence = np.max(predictions)

print("Predicted Disease:", predicted_class)
print("Confidence:", confidence)

import matplotlib.pyplot as plt

plt.imshow(img)
plt.title(f"{predicted_class} ({confidence:.2f})")
plt.axis('off')
plt.show()

top3 = np.argsort(predictions[0])[-3:][::-1]

print("\nTop 3 Predictions:")
for i in top3:
    print(f"{class_names[i]}: {predictions[0][i]:.3f}")